### ISSUE TITLE
socket.io

### ISSUE THREAD

**Issue by samselikoff** [thoov/mock-socket#17]
Does this work with socket.io? I've read somewhere that socket.io doesn't use standard websocket protocol

**Comment by thoov** [comment]
Hi @samselikoff. Unfortunately it does not currently support socket.io and you are right about socket.io not supporting the WebSocket spec. From (http://socket.io/blog/introducing-socket-io-1-0) "... Engine.IO that implements a **WebSocket-like** API". For some background, this library was build for my other project [ember-websockets](https://github.com/thoov/ember-websockets) and there I recommend using [ws](https://www.npmjs.com/package/ws). With all of this being said it would not be *too hard* to add support for socket.io as their global IO object tries to stay fairly close to the native websocket protocol. After a quick glance I believe the only thing really missing in this project is support for [rooms](http://socket.io/docs/rooms-and-namespaces/) which is not defined in the native websocket spec.

**Comment by samselikoff** [comment]
I see - thanks for the quick response!

If I wanted to take a stab at this, how would I start? Would I need to replace io.Socket (rather than window.Websocket)? I spent some time the other day trying to intercept the HTTP responses Socket.IO makes to establish the initial connection, but I couldn't get it working.

**Comment by thoov** [comment]
Websockets in the browser works like this:

You create a websocket instance via:

```js
var websocket = new WebSocket('ws://localhost:8000');
```

Here the `WebSocket` object does all the special stuff connecting to the backend and also handles how communication is handled from the client to the server and vise versa. This is done through the onopen, onmessage, onclose, and onerror methods. ie:

```js
var websocket = new WebSocket('ws://localhost:8000');

websocket.onmessage = function(messageObject) {
  alert('We have a message');
};
```

On the server you would most likely have something like this:

```js
var WebSocket = require('ws');
var ws = new WebSocket('ws://www.host.com/path');

ws.on('open', function open() {
  ws.send('something');
});
```

So where this library comes in is in 2 places. First is mocking the client `WebSocket` object. This is done via:

```js
window.WebSockets = MockSocket;
```

`MockSocket` tries to expose an identical API surface to the native `WebSocket` object but instead of doing all of the connection setup/network stuff it creates a connection with a fake server.

Moving over to Socket.IO you see that its client is build like so:

```js
var socket = io('http://localhost:8000');

socket.on('chat message', function(msg){
  alert('We have a message');
});

//vs

var websocket = new WebSocket('ws://localhost:8000');

websocket.onmessage = function(messageObject) {
  alert('We have a message');
};
```

Therefore the first thing would have to change is MockSocket would need to create this `on` function. That could be added [here](https://github.com/thoov/mock-socket/blob/master/src/helpers/websocket-properties.js#L20). Inside of that new `on` function you would have to listen for notifications from the fake server for a given room name (the room name in the above example is `chat message`).

After you did this you would have something like this:

```js
window.io = MockSocket;

var socket = io('http://localhost:8000');

socket.on('chat message', function(msg){
  alert('We have a message');
});
```

After this you would have to modify the `MockServer` object to broadcast notifications based on room names. As an example, Socket.IO does this:

```js
io.emit('chat message', msg);
```

You would need to modify this [send](https://github.com/thoov/mock-socket/blob/master/src/mock-server.js#L60) function to support sending with a room name.

There are a few other minor corner cases that I think you might run across but these 2 that I listed above are the biggest.

**Comment by samselikoff** [comment]
Excellent - thanks so much for the details response! Hopefully I'll have some time to dig into this soon. Would be great to get this working, as socket.io is still a super popular ws lib.

**Comment by thoov** [comment]
In my [ember-websockets project](https://github.com/thoov/ember-websockets/issues/23) I am looking to add Socket.IO support. If I do then I would most likely upgrade this library to support it *but* this is still in the idea stage and probably wont be ready in the short term.

**Comment by thoov** [comment]
I am closing this as #50 has been merged. It would be great if people could try using v 0.8.0 with socket.io so we can see if there are any bugs
