### ISSUE TITLE
Can't import SocketIO

### ISSUE THREAD

**Issue by pascal0002** [thoov/mock-socket#252]
import { Server, SocketIO } from "mock-socket";
Gives Error: Module '"mock-socket"' has no exported member 'SocketIO'.ts(2305)

**Comment by builder7777** [comment]
Any updates?

**Comment by CorwinMoyne** [comment]
Any updates?

**Comment by ronyf** [comment]
is this ever going to be solved?

**Comment by maxime1992** [comment]
@ronyf 

> is this ever going to be solved?

What do you expect from such an offensive question exactly?

Are you sponsoring this open source project in any active way that would even get close to a point where you'd be in a position to expect someone to spend time doing that for you or do you just feel like the universe and the repo owner owe you anything?

I'd say raise a pull request yourself but with your 3 contributions on Github in the past year it looks like ranting is your preferred weapon over contributing.

If you want something to be solved for you either:
- patiently and kindly wait for someone to do it for free, if and when they decide to
- offer money as a reward
- give some of your time to help in any way, like trying to find the root cause and fix it yourself or at least point to where it's happening and share what you've found so someone else can eventually pick it up

But keep in mind that maintainers have not begged you to use their project. They've kindly open sourced it, **for free**. They didn't sign a maintenance contract. Asking that kind of offensive question is **never** going to help.
