### ISSUE TITLE
server.on("connection", ...) returns the server instance instead of the client socket instance

### ISSUE THREAD

**Issue by brian-mann** [thoov/mock-socket#72]
Per this library it doesn't seem possible to simulate socket.io clients emitting events.

I can only emit events from the server.

``` javascript
var Server = require("mock-server").Server
var mockServer = new Server("http://localhost:1111")

mockServer.on("connection", function(socket){
  // socket === mockServer
  // this makes no sense. socket should be the
  // client socket which connected, not the server.

  // in the real socket.io lib, socket is the client instance
})
```

In my code, I attach event listeners to the socket which connected, and I'm trying to simulate those. Is this possible using another method?

**Comment by thoov** [comment]
@brian-mann Sorry for the delay in getting back to you on this and thanks for opening the issue. Could you attach the test that you are trying to write so I can use that as a test case?

**Comment by lgandecki** [comment]
This is still true, and for WebSocket as well. To be able to work with apollo  subscriptions-transport-ws  ( https://github.com/apollographql/subscriptions-transport-ws/pull/374 ) I've created a hacky fork ( https://github.com/thoov/mock-socket/compare/master...lgandecki:master ) for now, since it looks like you are rewriting this significantly I didn't think it was worth adding tests around it (although I haven't broken any). 

Could you tell me a bit what's your plan here? Are you going to push with the rewrite? Or have you decided to stay with the current architecture?

**Comment by hervispichardo** [comment]
Any updates on this?
